#!/bin/bash

set -euo pipefail
IFS=$'\n\t'

./maint/travis-dzil clean
./maint/travis-dzil build
rm -f *.tar.gz

cd Alien-Build-*

./maint/travis-daemon

perl Makefile.PL
make
if which yath; then
  prove -bvm t/00_diag.t
  yath test
else
  make test TEST_VERBOSE=1
fi
make install
