#!/bin/bash

source ${PERLBREW_ROOT}/etc/bashrc
DZIL_PERL_VERSION=5.24
perlbrew use $DZIL_PERL_VERSION

set -euo pipefail
IFS=$'\n\t'

PREFIX=~/mylib/dzil

function dzil {
  perl -I$PREFIX/lib/perl5 $PREFIX/bin/dzil $@
}

if [ ! -e ~/.travis-dzil-first ]; then
  if [ ! -e ~/mylib/dzil/.perl-$DZIL_PERL_VERSION ]; then
    rm -rf ~/mylib/dzil
  fi
  cpanm --reinstall -n -l $PREFIX Dist::Zilla
  cpanm -n -l $PREFIX Archive::Tar::Wrapper
  dzil authordeps --missing | cpanm -l $PREFIX -n
  dzil listdeps   --missing | cpanm -l $PREFIX -n
  touch ~/.travis-dzil-first
  touch ~/mylib/dzil/.perl-$DZIL_PERL_VERSION
fi

dzil $@
