#!/bin/bash

set -euo pipefail
IFS=$'\n\t'

cd corpus

rm -rf libpalindrome
rm -rf cmake-libpalindrome
git clone https://github.com/plicease/cmake-libpalindrome.git

cd cmake-libpalindrome
rm -rf .git*
cd ..

